#############################################################################
# Makefile for building: debug/QTFractal
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Jan 16 15:58:12 2013
# Project:  QTFractal.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile QTFractal.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -Igenerated
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = debug/

####### Files

SOURCES       = src/iterated_fractal.cc \
		src/main.cc \
		src/mandelbrot.cc \
		src/palette.cc \
		src/result.cc \
		src/viewport.cc \
		src/qfractal_view.cc \
		src/julia.cc \
		src/qfractal_window.cc \
		src/fractal_manager.cc \
		src/palette_manager.cc \
		src/evaluator_manager.cc \
		src/bw_palette.cc \
		src/greyscale_palette.cc \
		src/linear_interpolator.cc \
		src/qview_panel.cc generated/moc_qfractal_view.cpp \
		generated/moc_qfractal_window.cpp \
		generated/moc_qview_panel.cpp
OBJECTS       = debug/iterated_fractal.o \
		debug/main.o \
		debug/mandelbrot.o \
		debug/palette.o \
		debug/result.o \
		debug/viewport.o \
		debug/qfractal_view.o \
		debug/julia.o \
		debug/qfractal_window.o \
		debug/fractal_manager.o \
		debug/palette_manager.o \
		debug/evaluator_manager.o \
		debug/bw_palette.o \
		debug/greyscale_palette.o \
		debug/linear_interpolator.o \
		debug/qview_panel.o \
		debug/moc_qfractal_view.o \
		debug/moc_qfractal_window.o \
		debug/moc_qview_panel.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QTFractal.pro
QMAKE_TARGET  = QTFractal
DESTDIR       = debug/
TARGET        = debug/QTFractal

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) debug/ || $(MKDIR) debug/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: QTFractal.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile QTFractal.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile QTFractal.pro

dist: 
	@$(CHK_DIR_EXISTS) debug/QTFractal1.0.0 || $(MKDIR) debug/QTFractal1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) debug/QTFractal1.0.0/ && $(COPY_FILE) --parents src/iterated_fractal.hh src/mandelbrot.hh src/palette.hh src/result.hh src/viewport.hh src/fractal.hh src/qfractal_view.hh src/julia.hh src/qfractal_window.hh src/fractal_manager.hh src/palette_manager.hh src/evaluator_manager.hh src/bw_palette.hh src/greyscale_palette.hh src/evaluator.hh src/linear_interpolator.hh src/qview_panel.hh debug/QTFractal1.0.0/ && $(COPY_FILE) --parents src/iterated_fractal.cc src/main.cc src/mandelbrot.cc src/palette.cc src/result.cc src/viewport.cc src/qfractal_view.cc src/julia.cc src/qfractal_window.cc src/fractal_manager.cc src/palette_manager.cc src/evaluator_manager.cc src/bw_palette.cc src/greyscale_palette.cc src/linear_interpolator.cc src/qview_panel.cc debug/QTFractal1.0.0/ && (cd `dirname debug/QTFractal1.0.0` && $(TAR) QTFractal1.0.0.tar QTFractal1.0.0 && $(COMPRESS) QTFractal1.0.0.tar) && $(MOVE) `dirname debug/QTFractal1.0.0`/QTFractal1.0.0.tar.gz . && $(DEL_FILE) -r debug/QTFractal1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: generated/moc_qfractal_view.cpp generated/moc_qfractal_window.cpp generated/moc_qview_panel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) generated/moc_qfractal_view.cpp generated/moc_qfractal_window.cpp generated/moc_qview_panel.cpp
generated/moc_qfractal_view.cpp: src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/qfractal_view.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qfractal_view.hh -o generated/moc_qfractal_view.cpp

generated/moc_qfractal_window.cpp: src/qfractal_view.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/fractal_manager.hh \
		src/evaluator.hh \
		src/result.hh \
		src/palette_manager.hh \
		src/evaluator_manager.hh \
		src/qfractal_window.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qfractal_window.hh -o generated/moc_qfractal_window.cpp

generated/moc_qview_panel.cpp: src/qfractal_view.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/qview_panel.hh
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qview_panel.hh -o generated/moc_qview_panel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

debug/iterated_fractal.o: src/iterated_fractal.cc src/iterated_fractal.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/evaluator.hh \
		src/result.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/iterated_fractal.o src/iterated_fractal.cc

debug/main.o: src/main.cc src/qfractal_window.hh \
		src/qfractal_view.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/fractal_manager.hh \
		src/evaluator.hh \
		src/result.hh \
		src/palette_manager.hh \
		src/evaluator_manager.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/main.o src/main.cc

debug/mandelbrot.o: src/mandelbrot.cc src/mandelbrot.hh \
		src/iterated_fractal.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/evaluator.hh \
		src/result.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/mandelbrot.o src/mandelbrot.cc

debug/palette.o: src/palette.cc src/palette.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/palette.o src/palette.cc

debug/result.o: src/result.cc src/result.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/result.o src/result.cc

debug/viewport.o: src/viewport.cc src/viewport.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/viewport.o src/viewport.cc

debug/qfractal_view.o: src/qfractal_view.cc src/qfractal_view.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/qfractal_view.o src/qfractal_view.cc

debug/julia.o: src/julia.cc src/julia.hh \
		src/iterated_fractal.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/evaluator.hh \
		src/result.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/julia.o src/julia.cc

debug/qfractal_window.o: src/qfractal_window.cc src/qfractal_window.hh \
		src/qfractal_view.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/fractal_manager.hh \
		src/evaluator.hh \
		src/result.hh \
		src/palette_manager.hh \
		src/evaluator_manager.hh \
		src/qview_panel.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/qfractal_window.o src/qfractal_window.cc

debug/fractal_manager.o: src/fractal_manager.cc src/fractal_manager.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh \
		src/evaluator.hh \
		src/result.hh \
		src/mandelbrot.hh \
		src/iterated_fractal.hh \
		src/julia.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/fractal_manager.o src/fractal_manager.cc

debug/palette_manager.o: src/palette_manager.cc src/palette_manager.hh \
		src/palette.hh \
		src/bw_palette.hh \
		src/greyscale_palette.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/palette_manager.o src/palette_manager.cc

debug/evaluator_manager.o: src/evaluator_manager.cc src/evaluator_manager.hh \
		src/evaluator.hh \
		src/result.hh \
		src/linear_interpolator.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/evaluator_manager.o src/evaluator_manager.cc

debug/bw_palette.o: src/bw_palette.cc src/bw_palette.hh \
		src/palette.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/bw_palette.o src/bw_palette.cc

debug/greyscale_palette.o: src/greyscale_palette.cc src/greyscale_palette.hh \
		src/palette.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/greyscale_palette.o src/greyscale_palette.cc

debug/linear_interpolator.o: src/linear_interpolator.cc src/linear_interpolator.hh \
		src/evaluator.hh \
		src/result.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/linear_interpolator.o src/linear_interpolator.cc

debug/qview_panel.o: src/qview_panel.cc src/qview_panel.hh \
		src/qfractal_view.hh \
		src/fractal.hh \
		src/viewport.hh \
		src/palette.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/qview_panel.o src/qview_panel.cc

debug/moc_qfractal_view.o: generated/moc_qfractal_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/moc_qfractal_view.o generated/moc_qfractal_view.cpp

debug/moc_qfractal_window.o: generated/moc_qfractal_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/moc_qfractal_window.o generated/moc_qfractal_window.cpp

debug/moc_qview_panel.o: generated/moc_qview_panel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug/moc_qview_panel.o generated/moc_qview_panel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

